/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'blockedUsers' : IDL.Vec(IDL.Principal),
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'academicDetails' : IDL.Text,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'document' : IDL.Opt(ExternalBlob),
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
  }),
  'reportedContent' : IDL.Opt(IDL.Text),
  'reportedUser' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
  'reporter' : IDL.Principal,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addSharedNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createForumPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'createStudyGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteForumPost' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'deletePostByAuthor' : IDL.Func([IDL.Nat], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPostComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getUserComments' : IDL.Func([IDL.Principal], [IDL.Vec(Comment)], ['query']),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'reportContent' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'reviewReport' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'resolved' : IDL.Null,
          'pending' : IDL.Null,
          'reviewed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updatePost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'blockedUsers' : IDL.Vec(IDL.Principal),
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'academicDetails' : IDL.Text,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'document' : IDL.Opt(ExternalBlob),
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'resolved' : IDL.Null,
      'pending' : IDL.Null,
      'reviewed' : IDL.Null,
    }),
    'reportedContent' : IDL.Opt(IDL.Text),
    'reportedUser' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'reporter' : IDL.Principal,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addSharedNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createForumPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'createStudyGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteForumPost' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'deletePostByAuthor' : IDL.Func([IDL.Nat], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPostComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getUserComments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'reportContent' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'reviewReport' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'resolved' : IDL.Null,
            'pending' : IDL.Null,
            'reviewed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updatePost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };