/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Post {
  'id' : bigint,
  'content' : string,
  'video' : [] | [ExternalBlob],
  'author' : Principal,
  'likes' : Array<Principal>,
  'document' : [] | [ExternalBlob],
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export interface Report {
  'id' : bigint,
  'status' : { 'resolved' : null } |
    { 'pending' : null } |
    { 'reviewed' : null },
  'reportedContent' : [] | [string],
  'reportedUser' : [] | [Principal],
  'timestamp' : Time,
  'reporter' : Principal,
  'reason' : string,
}
export interface StudyGroup {
  'id' : bigint,
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'description' : string,
}
export interface StudyGroupMessage {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'blockedUsers' : Array<Principal>,
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'academicDetails' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'addSharedNote' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createForumPost' : ActorMethod<[string, string], undefined>,
  'createPost' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [ExternalBlob], [] | [ExternalBlob]],
    undefined
  >,
  'createStudyGroup' : ActorMethod<[string, string], undefined>,
  'createUserProfile' : ActorMethod<[string, string, string], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteForumPost' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deletePostByAuthor' : ActorMethod<[bigint], undefined>,
  'getAllStudyGroups' : ActorMethod<[], Array<StudyGroup>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeed' : ActorMethod<[], Array<Post>>,
  'getPostComments' : ActorMethod<[bigint], Array<Comment>>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getStudyGroup' : ActorMethod<[bigint], [] | [StudyGroup]>,
  'getStudyGroupMessages' : ActorMethod<[bigint], Array<StudyGroupMessage>>,
  'getUserComments' : ActorMethod<[Principal], Array<Comment>>,
  'getUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinStudyGroup' : ActorMethod<[bigint], undefined>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'reportContent' : ActorMethod<
    [[] | [Principal], [] | [string], string],
    undefined
  >,
  'reviewReport' : ActorMethod<
    [
      bigint,
      { 'resolved' : null } |
        { 'pending' : null } |
        { 'reviewed' : null },
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'sendStudyGroupMessage' : ActorMethod<[bigint, string], undefined>,
  'updatePost' : ActorMethod<
    [
      bigint,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];